### ISSUE TITLE
Thoughts about the checksum field

### ISSUE THREAD

**Issue by jwerner-chromium** [FirmwareHandoff/firmware_handoff#13]
@danh-arm @jmarinho @sjg20

I was recently thinking about some possible use cases for the transfer list specification and I think I have some concerns about the checksum field, I thought it might be worth discussing these while we're still in the "v0.9 probation period". The checksum may be fine for normal informational records that get added to the TL once and then mostly stay unchanged forever, but not all use cases may necessarily be like that. A classic example would be something like an in-memory firmware log (e.g. the "CBMEM console" we have in coreboot) that constantly writes more lines into the TE data area for every printf() call. It would be pretty inefficient to recalculate the checksum on the fly every time a new line gets logged, and from an architectural point of view it is likely that the subsystem which modifies the buffer (e.g. the logging code in this example) may want to remain agnostic of where exactly the buffer is stored and that this storage backend has specific requirements about extra steps that need to be done whenever something is updated.

Of course a solution could be that we let the checksum lapse for a bit and then only recalculate it at the end of a firmware stage right before we hand off to the next one. But this still adds a sort of unnecessary tax to adding large data buffers to the TL (e.g. a 128K console log like coreboot allocates by default, most of which is not actually used on most boots and thus just full of uninitialized data that would pointlessly need to get checksummed), particularly because our byte-at-a-time checksumming algorithm is very simple to implement but not really the fastest kind of memory checksum you can have on a 64-bit machine. There might also be a concern about different writers at different exception levels messing around in the same buffer at the same time, which may be okay for that specific buffer but maybe not for the TL metadata structures (e.g. on our Arm Chromebook systems both BL31 and BL33 are technically sharing the same CBMEM console buffer without concurrent access arbitration, which we accept because in practice having both try to log something at the same time is very unlikely and if it does happen the worst it's gonna do is a bit of console output corruption).

Does the checksum really give us enough real benefit to be worth the potential cost of making the TL unsuitable for certain applications? Or did we just include it because of some vague idea that it's "best practice" to have checksums for persistent data structures, without any real practical benefit for our particular design? I mean, the TL is generally just passed around in memory within a single boot cycle, and memory normally doesn't get random bit errors out of nowhere. What kind of corruption are we actually worried about that we want the checksum to guard against?

If we do believe that the checksum is important for certain use cases, should we maybe consider offering both options (e.g. differentiated by different magic numbers) to allow applications to choose whether maintaining a checksum is worth the cost for them?

**Comment by sjg20** [comment]
When jumping from one binary to another it is quite easy for something to get overwritten, e.g. some bytes in the middle of a data structure, so I think the checksum is useful. But I agree that if everything is working perfectly then it is not needed (by definition, I suppose)

The U-Boot bloblist implementation only checksummed the data portion...it is slightly more complicated code (must loop through the TEs one at a time), but if performance is a consideration, we could perhaps go back to that. We could then have a TE flag to indicate that a TE's data should not be checksummed, for the case you mention where the data itself is not that critical.

I am OK with offering both options, but I think it should be done with a flag in the TL header.

**Comment by jwerner-chromium** [comment]
> There's space in the TL header for this.

There isn't actually, the current TL header is exactly 16 bytes. We'd have to bump it to 24 or steal some bits from one of the other fields.

> I think it would be overkill to allow skipping the checksum on a TE by TE basis. There's currently no space in the TE header for this anyway.

I think one option could be to integrate this into the tag ID itself. Usually, the type of tag should indicate whether it makes sense to checksum this or not anyway (e.g. a tag with a small informational structure that describes the serial console on the platform is something everyone would want to checksum, whereas a tag that contains an in memory console log is probably something nobody would ever want to checksum). So we could say that the highest bit (bit 23) of the tag ID indicates whether the tag should be checksummed (0) or not (1), and contributors would make that decision when allocating a new tag. (We'd then want to split the non-standardized tag range in two so there are non-standardized tags of both kinds available for use.)

Anyway, I'm fine with either option and happy to write up a PR for this if we all agree that we want to do this. (Note that this would be a backwards-incompatible change either way, even without the TL header space issue, because it changes the checksum and therefore would make it invalid for old readers.)

(Also, while we're discussing backwards-incompatible checksum changes, should we maybe also consider changing the checksum algorithm to something that can read more bytes at once? Byte-at-a-time algorithms are pretty inefficient on 64-bit machines, and we have the unique opportunity to know that everything we'll checksum will always be 8-byte aligned anyway. If we just change from "sum of all bytes" to "XOR of all bytes", the definition would be just as simple, but the implementation could do it in 8-byte chunks and then just narrow down to one byte at the end, while preserving other properties like the ability to add/subtract individual parts without recomputing the whole.)

**Comment by sjg20** [comment]
I don't like the idea of adding flags to the tag...we have already trimmed this down to 24 bytes and it seems hacky to fiddle with it further.  Will the next flag go there too? I agree that a TE-level checksum flag seems overkill.

We deliberate chose to leave no space in the headers, but with an out, that we can adjust it if something comes up. I would support going back to a 32-byte TL header with a 32-bit flag word, of which one bit could control whether the TL uses checksums.

Re the algo, I am not sure how much it matters. The current algo is simple and perhaps slightly more useful than an xor (although this is only from dim, dark memory so I could be wrong). At least on ARM you can sum the bytes of a word...although probably the compiler would not figure that out.

So perhaps this is a good opportunity to use the 'out' we gave ourselves.

**Comment by danh-arm** [comment]
> There isn't actually [space in the TL header]

Sorry, I miscounted the bytes.

> Note that this would be a backwards-incompatible change either way

Agreed

I'm not keen on re-interpreting the tag ID either. If we need this it should be explicitly described in a separate TE/TL header field. If we want to retain the current TE/TL header sizes then we'll need to get creative on the current structures. Current fields are currently all an integer number of bytes in size but I guess they don't have to be. For example, if the hdr_size described the number of 8-byte blocks (instead of the number of bytes) then we wouldn't need a whole byte for this. Similarly, we don't need to support 2^256 byte alignments. I doubt we need 4 bytes for the signature either; I've just noticed the value of the top byte is 0 anyway (I think we should change this).

If we do need a bigger TL header then I guess we don't have to choose a power-of-2 size. 24-bytes (8-byte aligned) would work. 

Julius: I'm not sure how important per-TE support for checksumming is to you but feel free to propose a new header structure. I would feel more comfortable if we had some zero-initialized reserved space in the headers to help make future binary compatible changes.

Regarding the checksumming algorithm, I can see using XOR would be more efficient but I'm not sure efficiency is the most important thing here. I'd prefer a standard algorithm like CRC or Adler, which would be better at detecting errors, though slower.

**Comment by jwerner-chromium** [comment]
>  I doubt we need 4 bytes for the signature either; I've just noticed the value of the top byte is 0 anyway (I think we should change this).

Well, that's kinda equivalent to the "new signature" suggestion I made at first. We could split the signature into 3 bytes static signature and 1 byte "flags that make it incompatible for both reading and writing", and if a consumer doesn't recognize a flag combination they consider it not a valid TL as they should. This would mean the existing v0.9 implementations could continue working (if we don't change the checksum algorithm), if we care about that. I'm fine with adding 8 more bytes to the header too, though.

I think both the 0x00 and the 0xff in the signature are probably suboptimal, if we want to change it entirely. Most importantly, the current signature misses an opportunity to spell out something clever in hex or ASCII. ;)

> The current algo is simple and perhaps slightly more useful than an xor (although this is only from dim, dark memory so I could be wrong).

Well, the sum would detect cases where two copies of the exact same TE are added to the TL whereas XOR doesn't, for example. But I don't think that's particularly relevant to our use case (if we're mostly worried about memcpy errors like Dan said). Both XOR and sum are very bad checksums if you really want to be able to detect complicated (i.e. non-random) differences (e.g. neither can detect the case where the order between two TEs was simply flipped), but I do think speed and simplicity of implementation are an important factor, and we should keep in mind what we're actually trying to protect against before we just decide that we need the "best" algorithm. Both sum and XOR also have the nice property that when you make an inline change (e.g. just delete or add a single TE in a large TL), you can "update" the checksum based on only the bytes you touched and don't have to recompute the whole thing. I think this might be useful for cases where the TL is passed through several small stages that each only need to make a minor modification.

> Also, Armv8-A has a CRC32 instruction.

I guess that would be another good way to make sure it's fast, but the thing to keep in mind about hardware acceleration is that relying on that hurts the architecture-independence of this specification. Although it looks like recent (~last 10 years-ish) x86 processors also contain a CRC instruction for at least one of the same polynomials as Arm, so as long as we pick that one maybe that point isn't very relevant in practice (depending on whether we think this might extend to embedded RISC-V applications).

**Comment by sjg20** [comment]
So where are we going with this?

FWIW I don't really like crc32 since in s/w it requires a lookup table

Let's add 8 bytes to the header, then, say with with a 32-bit flags word and all but bit 0 (checksum valid) reserved?

**Comment by sjg20** [comment]
Any thoughts on this? I can send a PR perhaps

**Comment by jwerner-chromium** [comment]
Sorry, just trying to find some time to write this up. Note that CRC32 doesn't require a lookup table, that's just the most common (because fastest) implementation, but it is perfectly possible to write very small and simple byte-by-byte CRC32 functions (e.g. https://review.coreboot.org/plugins/gitiles/coreboot/+/refs/heads/master/src/lib/crc_byte.c#27). If we think that a strong checksum is necessary and you don't think the advantages I mentioned about sum and XOR (being able to easily update an existing checksum after small modifications without having to recalculate everything) are relevant, then I think I agree with Dan that due to the prevalent hardware support CRC32 (with polynomial 0x11EDC6F41) would be the best option.

**Comment by sjg20** [comment]
Ugh that is a bitwise algorithm, pretty slow. I actually am not sure that having a 'secure' checksum is that important...it is mostly just a sanity check. If we want it secure we should probably use a hash. No, I am not suggesting we do that.

I do quite like the existing sum approach since it is very simple and it is possible to add something and update the checksum, as you say.

In any case, what do you think about the flags side of things?

**Comment by jwerner-chromium** [comment]
> Ugh that is a bitwise algorithm, pretty slow.

Right, I think the assumption is that almost everyone could be using the AArch64 or amd64 acceleration instructions so this wouldn't matter much (although it's nice than an easy fallback to software is available if necessary).

> I actually am not sure that having a 'secure' checksum is that important...it is mostly just a sanity check. If we want it secure we should probably use a hash.

There's still a big difference between "detects a lot of accidental corruption" and cryptographically secure. I don't think anybody here is suggesting a cryptographic hash. But I agree that I don't think we need to be particularly worried about all those more subtle kinds of accidental corruption (e.g. cases like switching the order of TEs, where sum and XOR would fail) either, since I think we are mostly worried about the very blatant and obvious "you accidentally overwrote part of this with something else" corruption.

> I do quite like the existing sum approach since it is very simple and it is possible to add something and update the checksum, as you say.

I think sum sits in the middle between XOR and CRC32 as having not quite the advantages of either, so I think it's not a good option. It has pretty much the same (very weak, but probably still good enough for us) error detection rate as XOR, and both are equally simple to implement, but XOR can run word-at-a-time and be much faster.

> In any case, what do you think about the flags side of things?

I think either option (take a byte out of the magic number or add 8 bytes) is fine. I agree with Dan that the magic number is suboptimal and might be worth changing anyway.

**Comment by sjg20** [comment]
> > Ugh that is a bitwise algorithm, pretty slow.
> 
> Right, I think the assumption is that almost everyone could be using the AArch64 or amd64 acceleration instructions so this wouldn't matter much (although it's nice than an easy fallback to software is available if necessary).
> 
> > I actually am not sure that having a 'secure' checksum is that important...it is mostly just a sanity check. If we want it secure we should probably use a hash.
> 
> There's still a big difference between "detects a lot of accidental corruption" and cryptographically secure. I don't think anybody here is suggesting a cryptographic hash. But I agree that I don't think we need to be particularly worried about all those more subtle kinds of accidental corruption (e.g. cases like switching the order of TEs, where sum and XOR would fail) either, since I think we are mostly worried about the very blatant and obvious "you accidentally overwrote part of this with something else" corruption.

Yes, that is what I have seen in practice.

> 
> > I do quite like the existing sum approach since it is very simple and it is possible to add something and update the checksum, as you say.
> 
> I think sum sits in the middle between XOR and CRC32 as having not quite the advantages of either, so I think it's not a good option. It has pretty much the same (very weak, but probably still good enough for us) error detection rate as XOR, and both are equally simple to implement, but XOR can run word-at-a-time and be much faster.

It is what smbios uses, so is familiar and simple. SUM can run word-at-a-time also, as per my previous reply.

> 
> > In any case, what do you think about the flags side of things?
> 
> I think either option (take a byte out of the magic number or add 8 bytes) is fine. I agree with Dan that the magic number is suboptimal and might be worth changing anyway.

OK let's do the 8 bytes one...should we set aside 4 of those bytes for flags and 4 reserved?

**Comment by jwerner-chromium** [comment]
> It is what smbios uses, so is familiar and simple. SUM can run word-at-a-time also, as per my previous reply.

Can you explain how? I don't see it. Is there some cool math trick I'm missing?

If you mean that you can just chunk the data into 4-byte words and add them all up and then consider the 4-byte result as your checksum, then yes, you can do that, but then that's not the same as the 1-byte sum anymore. That's a different checksum algorithm. The great thing about XOR is that you can chunk the data into any word size you want, XOR all those words together, and then XOR the individual bytes of the result word together, and you get a 1-byte result that is the same as if you had individually XORed every byte of the input data together. The code implementing the checksum can choose whether it wants the most simple option possible or a slightly more complicated but slightly faster implementation. The option of choosing the word size can be important because transfer lists might be used on both 32-bit and 64-bit architectures.

> OK let's do the 8 bytes one...should we set aside 4 of those bytes for flags and 4 reserved?

That sounds fine by me.

**Comment by sjg20** [comment]
> > It is what smbios uses, so is familiar and simple. SUM can run word-at-a-time also, as per my previous reply.
> 
> Can you explain how? I don't see it. Is there some cool math trick I'm missing?
> 
> If you mean that you can just chunk the data into 4-byte words and add them all up and then consider the 4-byte result as your checksum, then yes, you can do that, but then that's not the same as the 1-byte sum anymore. That's a different checksum algorithm. The great thing about XOR is that you can chunk the data into any word size you want, XOR all those words together, and then XOR the individual bytes of the result word together, and you get a 1-byte result that is the same as if you had individually XORed every byte of the input data together. The code implementing the checksum can choose whether it wants the most simple option possible or a slightly more complicated but slightly faster implementation. The option of choosing the word size can be important because transfer lists might be used on both 32-bit and 64-bit architectures.

No I meant the SIMD support that we see these days. E.g. for ARM I believe USADA8 can do it.

> 
> > OK let's do the 8 bytes one...should we set aside 4 of those bytes for flags and 4 reserved?
> 
> That sounds fine by me.

OK I'll send a PR once we have the checksum worked out.

**Comment by sjg20** [comment]
I don't know about that side of it...SMBIOS uses sum which is I believe why we went with that. I had imagined that sum was a better check, since 0 data would xor to 0. But that doesn't apply in this case.

So from my POV, if you prefer xor, let's do that. So an 8-bit xor value?

**Comment by jwerner-chromium** [comment]
> I had imagined that sum was a better check, since 0 data would xor to 0. But that doesn't apply in this case.

I mean, 0 data would also sum to 0. ;) If you're concerned specifically about the 0 case we could decide to use the complement of the XOR result instead, but I don't think that's necessary since we also have a magic number, so we can tell a valid TL apart from a fully zeroed buffer anyway (which is usually the main problem about checksums that leave zeroes as zero).

sum is still slightly better in a few edge cases, e.g. if only a few random bits flip they are more likely to cancel out with XOR, and sum can detect things like adding the same extra block of data twice which would cancel out for XOR. But as discussed earlier, if you look at it from a theoretical "science of error detection" standpoint they're really both very bad, but for the kinds of large, random cases of corruption that I think we're concerned about here (e.g. half the data was cut off or some big chunk in the middle got accidentally overwritten), they should both be good enough.

> So from my POV, if you prefer xor, let's do that. So an 8-bit xor value?

Yes, let's just do that.

**Comment by sjg20** [comment]
https://github.com/FirmwareHandoff/firmware_handoff/pull/17

**Comment by sjg20** [comment]
I still need to change this to xor...but this is a start

**Comment by danh-arm** [comment]
Sorry for the delay in coming back to this. Thanks for starting the PR, Simon. I'll review it tomorrow.
Regarding, the checksum algo, I agree the property of being easy to update when the TL changes is good. I don't feel strongly between simple sum and XOR but if you want to change it then fine.

**Comment by danh-arm** [comment]
Fixed by #17
