### ISSUE TITLE
size and max_size

### ISSUE THREAD

**Issue by sjg20** [FirmwareHandoff/firmware_handoff#22]
I am not sure I like the use of 'size' and 'max_size' in the TL header.

The TL size is really the size that it takes up in memory. Some of that size is taken up by TEs. Some (at the end) may be spare.

Having to refer to 'max size' all the time is confusing, I think. I suggest the following terminology:

size - size of the TL data structure, comprising TEs and empty space
alloced (or used?) - number of bytes which are allocated for TEs, meaning that there may be free bytes at the end

This terminology is more similar to malloc() and avoids the size / max_size confusion.

What do you think?

**Comment by jwerner-chromium** [comment]
I think since there seems to be no general consensus on what a field that's just called `size` means in this context, it would be best to not use that at all. How about `used_size` and `max_size`?

**Comment by sjg20** [comment]
I'm not really keen on the word 'max'. We are not in a situation where size can change to max_size without some sort of allocation. It just seems like odd terminology to me.

Personally I would prefer to avoid 'size' with the 'used' name, since 'used' is not really a size of anything. It is just the number to used bytes. But at least what you suggest is better than what we have.

How about used (or used_size if you really like that) and total_size?

**Comment by jwerner-chromium** [comment]
I think `used_size` and `total_size` seems reasonable. (If you really don't like "size", I guess `used_bytes` and `total_bytes` would also work. I think it would be good to have something matching in both to indicate that they are related.)

**Comment by sjg20** [comment]
OK thanks I will do a PR for used_size and total_size
