### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by thomas-fossati** [FirmwareHandoff/firmware_handoff#27]
There seems to be an implicit promise of eternal backwards compatibility [here](https://github.com/FirmwareHandoff/firmware_handoff/blob/29aeb41bd8e023bdc12ca6262bd1fe881f62d55c/source/transfer_list.rst?plain=1#L80), specifically:

> _"[...] Code that encounters a TL with a version higher than it knows to support may still read the TL and all its TEs, and assume that it is backwards-compatible to previous versions [...]"_

Alternatively, the version field could be split into major/minor with clear SemVer-like semantics regarding the compatibility assumptions of a given version.

(Note that the current 0x01 would be interpreted as v0.1 which does not look entirely unreasonable.)

**Comment by sjg20** [comment]
Version numbering is not a great solution, IMO. What is the goal?

To change a TE into something incompatible we can create a new TE (tag) with what we want, leaving the old one alone.

The challenges with breaking backwards compatibility is that private binaries are often not updated, so you are stuck with them, perhaps for many years.

**Comment by thomas-fossati** [comment]
> Version numbering is not a great solution, IMO.

The version field existed already when I bumped into it, I didn't make it up :-)

> What is the goal?

I suppose the aim is to guide the recipient's parsing code on traversing the header and payload information elements.  At least, this is the usual purpose of such fields.

> To change a TE into something incompatible we can create a new TE (tag) with what we want, leaving the old one alone.

But that's a different story, adding a new TE does not change the header structure.  What I am referring to in this issue is the TL header's version field.

**Comment by sjg20** [comment]
> > Version numbering is not a great solution, IMO.
> 
> The version field existed already when I bumped into it, I didn't make it up :-)

Sure, it's just that I don't think it helps much to have minor/major stuff.

> 
> > What is the goal?
> 
> I suppose the aim is to guide the receiver's parsing code on traversing the header and payload information elements. At least, this is the usual purpose of such fields.

Yes, sure.

> 
> > To change a TE into something incompatible we can create a new TE (tag) with what we want, leaving the old one alone.
> 
> But that's a different story: adding a new TE does not change the header structure. What I am referring to in this issue is the TL header's version field.

Me too. We don't want to create a TL (in the future) which cannot be read by software built in the past. So the external backwards compatibility is by design.

**Comment by thomas-fossati** [comment]
Thanks for taking the time to explain to me what should have been clear if I had read the beginning of §2.2 more carefully :-), i.e., that eternal backward compatibility is by design.

**Comment by sjg20** [comment]
Thank you for raising it.  It you can tweak the language to be better, please do

**Comment by jwerner-chromium** [comment]
FYI we had that discussion about the version field earlier and decided that it was unnecessary to add a "major version" (meaning backwards-incompatible), because if we ever wanted to make such a change (which is unlikely because the whole goal here is to create a stable ecosystem) we could just change the signature magic number instead.
