### ISSUE TITLE
register_conventions should be updated to aligned to the 4-byte TL signature

### ISSUE THREAD

**Issue by raymo200915** [FirmwareHandoff/firmware_handoff#32]
Commit [d6afd9b](https://github.com/FirmwareHandoff/firmware_handoff/pull/24/commits/d6afd9b9aaaed901dcda4744003ab037e21a4e63) updated the signature from 3 bytes to 4 bytes, but didn't update the register_conventions accordingly.
TL signature should be placed to X1[31:0], while version of the register convention should be placed to X1[39:32].

**Comment by manish-pandey-arm** [comment]
Thanks Raymond to bringing this issue, we recently found this issue and sorry for overlooking it.

We need to make changes in register convention to fix the issue, i have got few ideas, Lets see what others think @sjg20 @jmarinho 
1. For both AArch64 and AArch32, just take 3 least bytes of signature and top byte from version
2. For AArch64 use whole 5 bytes (as suggested by you) and for AArch32 use option 1 (this will have deviation between Archs)
3. Do XoR of signature and version.

Based on feedback i will post a PR

**Comment by danh-arm** [comment]
I'd vote for 2. I don't think deviation between AArch64/AArch32 is a big deal.

**Comment by jmarinho** [comment]
Just making a note that all people that commented on this issue (so far) accept option 2 as the solution.
Should we commit to that?

**Comment by manish-pandey-arm** [comment]
Thanks all! I will post a patch soon.
